Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.linked_clone = true
  end
  config.vm.box = "generic/fedora39"
  config.vm.define "fedora" do |fedora|
    fedora.vm.hostname = "fedora"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.raw_arguments = [
      "-v"
    ]
    ansible.groups = {
      "workstations" => ["fedora"],
      "red_hat" => ["fedora"]
    }
  end
end
