---
- name: Ensure yum repos path exists
  file:
    path: "{{ yum_repos_path }}"
    state: directory
  when: ansible_os_family == "RedHat"

- name: Install repos files
  copy:
    src: "{{ item }}"
    dest: "{{ yum_repos_path }}/{{ item | basename }}"
  with_fileglob: '*.repo'
  when: ansible_os_family == "RedHat"

- name: Ensure jEdit home path exists
  file:
    path: "{{ jedit_home_path }}"
    state: directory
  become: false
  when: ansible_os_family == "RedHat"

- name: Install jedit config file
  copy:
    src: "{{ item }}"
    dest: "{{ jedit_home_path }}/{{ item | basename }}"
  with_fileglob: 'jedit/*'
  become: false
  when: ansible_os_family == "RedHat"

- name: Install packages
  package:
    name:
      - code
      - jedit
